# DataFrame
- 행열을 가진 2차원 자료구조
- 여러개의 Series 묶음 자료형

In [ ]:
import pandas as pd
import numpy as np
from altair.vegalite.v6 import display
from pandas import Series

In [ ]:
# dict -> df생성
data = {"one": [1.0, 2.0, 3.0], "two": [10, 20, 30], "three": 99}

# dict의 각 item이 하나의 Series로 처리됨
df = pd.DataFrame(data)
print(df['one'])  # one 열에 있는 Series를 선택
df

In [ ]:
# 여러 개의 dict -> dataframe
data: list[dict[str, int]] = [{
    "a": 10,
    "b": 20,
}, {
    "a": 30,
    "b": 40,
    "c": 50,
}]

# 하나의 dict -> 하나의 레코드, key는 컬럼으로 처리
df = pd.DataFrame(data)
df  # 0번행의 c열의 NaN = 결측치

In [ ]:
arr = np.arange(9).reshape(3, 3)
df = pd.DataFrame(arr, columns=('a', 'b', 'c'), index=['1일', '2일', '3일'])
df

# arr_a = [
#     [1, 2, 3],
#     [4,5,6]
#     ,[7,8,9]
# ]
# arr_a

In [ ]:
name_ser = pd.Series(['홍길동', "이순신", "감강찬"])
age_ser = pd.Series([20, 30, 40])

df = pd.DataFrame({"name": name_ser, "age": age_ser})
df

## DataFrame 생성

In [ ]:
# tuple(record) -> dataframe
# 하나의 객체
data = [
    ('홍길동', 20),
    ('이순신', 30),
    ('논개', 43),
]
df = pd.DataFrame.from_records(data, columns=['이름', '나이'])
df

## DataFrame 속성

In [ ]:
data = {
    'Bank client ID': [1, 2, 3, 4],
    'Bank Client Name': ['Laila Aly', 'Kate Steve', 'Nicole Mitch', 'Francis Morris'],
    'Net worth [$]': [35000, 3000, 100000, 2000],
    'Years with bank': [4, 7, 10, 15]
}
df = pd.DataFrame(data)
df

In [ ]:
df.info()
print(df.columns)
print(df.describe())

In [ ]:
print(df.dtypes)
print(df.shape)
print(df.size)

## DataFrame 메서드

In [ ]:
# head(n), tail(n) : 최상위 n개 , 최하위 n개
# display(df.head(2))
# display(df.tail(2))

In [ ]:
# values_counts(): 유일값 분포 확인
# display()
df['Years with bank'].value_counts()
# df.value_counts()

In [ ]:
# index 재지정 : 특정 컬럼을 인덱스로 지정
df.set_index('Bank client ID')

## 조회
- 행열조회
    - df.iloc[인덱스]
    - df.loc[라벨]
- 열조회
    - df[컬럼명]

In [ ]:
dicts = [
    {'name': '홍길동', 'job': '강사', 'age': 33},
    {'name': '신사임당', 'age': 44, 'job': '영업사원'},
    {'name': '이순신', 'age': 38, 'job': '장군'},
    {'name': '논개', 'age': 25, 'job': '개발'},
    {'name': '강감찬', 'age': 47, 'job': '교수'},
]
df = pd.DataFrame(dicts)
df

In [ ]:
print(df.iloc[0])
print(type(df.iloc[0]))  # 시리즈, 데이터프레임에서 한행 또는 한 열은 시리크 타입
print(df.loc[0].index)
print(df.iloc[0].name)

In [ ]:
# 슬라이싱 지워
df2 = df.iloc[0:2]
df2

### iloc (인덱스 위치)

In [ ]:
# fancy indexing 지원
df.iloc[[0, 2]]

In [ ]:
# 단일값 조회
print(df.iloc[0, 1])

# 여러 행 조회
df.iloc[0:2, 1]

In [ ]:
df2 = df.iloc[:2, :2]
print(type(df2))
df2

### loc
인데스라벨을 통해 조회

In [ ]:
# index명 지정 == 라벨링
df.index = ['client1', 'client2', 'client3', 'client4', 'client5']
df

In [ ]:
df.loc['client4']  # 1행만 나오므로 시리즈 타입

In [ ]:
# 인덱싱 하여 키를 제거하고 직접넣었기 때문에 key error 발생
# df.loc[3]

In [ ]:
# loc를 이룡한 컬럼 단일값 조회
print(type(df.loc['client2', 'job']))
print(df.loc['client2', 'job'])

# loc를 이용한 슬라이싱
print(df.loc['client2':'client4'])

print()
# loc를 이용한 슬라이싱
print(df.loc['client2':'client4', 'job'])

print()
# loc를 이용한 슬라이싱
print(df.loc['client2':'client4', 'job':])

### 컬럼라벨

In [ ]:
# df['컬럼명'] : 해당 컬럼 시리즈 반환
print(type(df['name']))
df['name']

In [ ]:
# fancy 인덱싱 : 조건값을 넣어서 팬시인덱승 가능
df[['name', 'job']]

In [ ]:
# loc + 컬럼 라벨
# print(df['name'])
print()
print(df['name'] == '논개')
print()

print(df.loc[df['name'] == '이순신'])

In [ ]:
# boolean indexing 비교연산
print(df['age'] > 30)
print('#' * 30)
print(df[df['age'] > 30])

In [ ]:
df

In [ ]:

# print( (df['job'] == '개발') & df['age'] < 30)
df.loc[(df['age'] < 30) & (df['job'] == '개발')]

In [ ]:
# - 이름에 '신'이 들어가거나 나이가 40대이상 조회
df[(df['age'] >= 40) | (df['name'].str.contains('신'))]

## 행 추가/삭제

In [ ]:
students = [
    {'name': '홍길동', 'midterm': 95, 'final': 85},
    {'name': '신사임당', 'midterm': 85, 'final': 80},
    {'name': '이순신', 'midterm': 10, 'final': 30}
]
df = pd.DataFrame(students)
df

In [45]:
# 중복되지 않는 인덱스
next_index = len(df)
print(next_index)

# 추가된 행의 filal 누락한 경우 결측치가 들어간다
# df.loc[next_index] = pd.Series({'name': '감상찬', 'midterm': 88, 'final': 85})
# df.loc[next_index] = pd.Series({'name': '감상찬', 'midterm': 88})
df

3

   name  midterm  final  mean
0   홍길동       95   85.0  90.0
1  신사임당       85   80.0  82.5
2   이순신       10   30.0  20.0

In [52]:
# 중복된 인덱스
next_index = 3
print(next_index)

# 추가된 행의 filal 누락
# df.loc[next_index] = pd.Series({'name': '감상찬', 'midterm': 88, 'final': 85})
df.loc[next_index] = pd.Series({'name': '율곡이이', 'midterm': 77})
df

3

   name  midterm  final  mean
0   홍길동       95   85.0  90.0
1  신사임당       85   80.0  82.5
2   이순신       10   30.0  20.0
3  율곡이이       77    NaN   NaN

In [58]:
# 행 삭제
# df = df.drop(3)
df

   name  midterm  final  mean
0   홍길동       95   85.0  90.0
1  신사임당       85   80.0  82.5

In [57]:
# 특정 조건을 만족하는 모든 행 삭제
# df = df[df['final' >= 60]] # 60점 이상만 남기기
df = df[df['final'] >= 60]
df

   name  midterm  final  mean
0   홍길동       95   85.0  90.0
1  신사임당       85   80.0  82.5

## 컬럼 추가/삭제

In [60]:
# df['phone'] = ['010-1234-1234', '010-5678-5678']
df.loc[:, 'phone'] = ['010-1234-1234', '010-5678-5678']
df

   name  midterm  final  mean          phone
0   홍길동       95   85.0  90.0  010-1234-1234
1  신사임당       85   80.0  82.5  010-5678-5678

In [56]:
# 중간,기말고사 평균 컬럼 추가
df.loc[:, 'mean'] = (df['midterm'] + df['final']) / 2
df

   name  midterm  final  mean
0   홍길동       95   85.0  90.0
1  신사임당       85   80.0  82.5

In [50]:
# 컬럼 삭제

# fancy 인덱싱
df[['name', 'midterm', 'final']]
df

   name  midterm  final  mean
0   홍길동       95   85.0  90.0
1  신사임당       85   80.0  82.5
2   이순신       10   30.0  20.0

In [66]:
df.loc[2] = {'name': '이순신', 'midterm': 10, 'final': 30}
df

   name  midterm  final  mean          phone   avg pass_fail
0   홍길동       95   85.0  90.0  010-1234-1234  90.0         P
1  신사임당       85   80.0  82.5  010-5678-5678  82.5         P
2   이순신       10   30.0   NaN            NaN   NaN       NaN

In [67]:
# ser|df.apply(함수)
# - 데이터프레임 또는 시리즈 객체의 각 요소에 함수를 적용할 때 사용
# - 데이터 전처리 시 자주 사용
def pass_or_fail(value):
    return 'P' if value >= 60 else 'F'


df.loc[:, 'avg'] = (df['midterm'] + df['final']) / 2
df.loc[:, 'pass_fail'] = df['avg'].apply(pass_or_fail)
df

   name  midterm  final  mean          phone   avg pass_fail
0   홍길동       95   85.0  90.0  010-1234-1234  90.0         P
1  신사임당       85   80.0  82.5  010-5678-5678  82.5         P
2   이순신       10   30.0   NaN            NaN  20.0         F

In [70]:
# apply 함수에 행(record) 전체를 인자로 전달해서 처리하기
def pass_or_fail2(record):
    avg = (record['midterm'] + record['final']) / 2
    return 'P' if avg >= 60 else 'F'


df.loc[:, 'pass_fail2'] = df.apply(pass_or_fail2, axis=1)
df

   name  midterm  final  mean          phone   avg pass_fail pass_fail2
0   홍길동       95   85.0  90.0  010-1234-1234  90.0         P          P
1  신사임당       85   80.0  82.5  010-5678-5678  82.5         P          P
2   이순신       10   30.0   NaN            NaN  20.0         F          F

## 정렬

In [75]:
# csv를 읽어와 df 생성
df = pd.read_csv('./data/bank_client_information.csv')
df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13

In [79]:
df.sort_values('Net Worth', ascending=False)
# df

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1

In [80]:
# 메인 정렬 중 같은 값이 존재하면 추가로 정렬 지정
df.sort_values(['Net Worth', 'Years with Bank'], ascending=[True, False])

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26

In [84]:
# 순위 부여
df.loc[:, 'Net Worth Rank'] = df['Net Worth'].rank(ascending=False).astype(int)
df.sort_values('Net Worth Rank', ascending=True)

,First Name,Last Name,Email,Postal Code,Net Worth,Years with Bank,Net Worth Rank
5,Samer,Mo,samer@gmail.com,J7H 3HY,100000.00,26,1
6,Heba,Ismail,heba.ismail@hotmail.com,K8Y 3M8,50000.00,11,2
7,Laila,Ahmed,Laila.a@hotmail.com,J8Y 3M0,20000.00,3,3
3,Chanel,Steve,chanel@gmail.com,N7T 3E6,11072.02,10,4
1,Noah,Small,nsmall@hotmail.com,N8S 14K,10000.00,6,5
2,Nina,Keller,azikez@gahew.mr,S1T 4E6,9072.02,7,6
9,Noah,Moran,guutodi@bigwoc.kw,K2D 4M9,8626.96,13,7
0,Bird,Steve,bird@gmail.com,N94 3M0,5000.00,5,8
4,Kate,Noor,kate@hotmail.com,K8N 5H6,5000.00,22,8
8,Joseph,Patton,daafeja@boh.jm,M6U 5U7,2629.13,1,10