# 집계처리 Aggregation
- 집계함수
- groupby()
- pivot_table()

In [1]:
import numpy as np
import pandas as pd
from IPython.display import display
from fontTools.subset.svg import group_elements_by_id
from selenium.webdriver.common.devtools.v147.page import print_to_pdf

# from IPython.display import display
display

In [3]:
data = {
    'name': ['김혜수', '박보검', '송혜교', '아이유', '공유', '전지현', '수지', '유재석', '강동원', '윤아'],
    'department': ['인사', '재무', '재무', 'IT', 'IT', '인사', '재무', '인사', 'IT', '재무'],
    'job': ['사원', '과장', '대리', '사원', '팀장', '대리', '대리', '과장', '사원', '팀장'],
    'branch': ['서울', '부산', '서울', '부산', '서울', '서울', '서울', '부산', '서울', '부산'],
    'salary': [3500, 5000, 4200, 3800, 6000, 4500, 4600, 5200, 3900, 6100],
    'hire_date': ['2020-03-15', '2018-07-10', '2019-05-20', '2021-01-10', '2017-09-25', '2019-03-05', '2020-06-12',
                  '2016-11-30', '2022-04-01', '2017-12-15']
}
emp_df = pd.DataFrame(data)

# 문자열 타입의 날짜를 pandas가 계산할 수 있는 날짜 타입(datetime)으로 변환
emp_df['hire_date'] = pd.to_datetime(emp_df['hire_date'])
emp_df
emp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     str
 1   department  10 non-null     str
 2   job         10 non-null     str
 3   branch      10 non-null     str
 4   salary      10 non-null     int64
 5   hire_date   10 non-null     datetime64[us]
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 861.0 bytes

In [7]:
display(emp_df.describe(include='all'))
display(emp_df.describe(include='str'))

       name department  job branch       salary            hire_date
count    10         10   10     10    10.000000                   10
unique   10          3    4      2          NaN                  NaN
top     김혜수         재무   사원     서울          NaN                  NaN
freq      1          4    3      6          NaN                  NaN
mean    NaN        NaN  NaN    NaN  4680.000000  2019-05-12 07:12:00
min     NaN        NaN  NaN    NaN  3500.000000  2016-11-30 00:00:00
25%     NaN        NaN  NaN    NaN  3975.000000  2018-02-04 18:00:00
50%     NaN        NaN  NaN    NaN  4550.000000  2019-04-12 00:00:00
75%     NaN        NaN  NaN    NaN  5150.000000  2020-05-20 18:00:00
max     NaN        NaN  NaN    NaN  6100.000000  2022-04-01 00:00:00
std     NaN        NaN  NaN    NaN   892.935235                  NaN

       name department job branch
count    10         10  10     10
unique   10          3   4      2
top     김혜수         재무  사원     서울
freq      1          4   3      6

## 집계함수

In [ ]:
print("count: ", emp_df['salary'].count())
print("min: ", emp_df['salary'].min())
print("max: ", emp_df['salary'].max())
# 평균으로부터 데이터가 퍼저있는 범위
print("var: ", emp_df['salary'].var())
# 표준편차는 분산과 같은 정보를 담고 있지만, 원래 데이터와 같은 단위로 바꿔서 사람이 이해하기 쉽게 만든 값이다.
# 평균으로부터 데이터가 실제로 얼마나 떨어져 있는지 나타내는 값
print("std: ", emp_df['salary'].std())
print("mean: ", emp_df['salary'].mean())
print("median: ", emp_df['salary'].median())
print("sum: ", emp_df['salary'].sum())

In [8]:
# 사분위수
print('0%', emp_df['salary'].quantile(0))
print('25%', emp_df['salary'].quantile(0.25))
print('50%', emp_df['salary'].quantile(0.5))
print('75%', emp_df['salary'].quantile(0.75))
print('100%', emp_df['salary'].quantile(1))

0% 3500.0
25% 3975.0
50% 4550.0
75% 5150.0
100% 6100.0

## groupby
- 데이터를 특정 기준에 따라 그룹화하여 집계 연산을 수행
- 컬럼을 기준으로 그룹화하여 집계 연산을 수행

In [13]:
display(emp_df)
dept = emp_df.groupby('department')
dept

  name department job branch  salary  hire_date
0  김혜수         인사  사원     서울    3500 2020-03-15
1  박보검         재무  과장     부산    5000 2018-07-10
2  송혜교         재무  대리     서울    4200 2019-05-20
3  아이유         IT  사원     부산    3800 2021-01-10
4   공유         IT  팀장     서울    6000 2017-09-25
5  전지현         인사  대리     서울    4500 2019-03-05
6   수지         재무  대리     서울    4600 2020-06-12
7  유재석         인사  과장     부산    5200 2016-11-30
8  강동원         IT  사원     서울    3900 2022-04-01
9   윤아         재무  팀장     부산    6100 2017-12-15

In [14]:
dept.groups

{'IT': [3, 4, 8], '인사': [0, 5, 7], '재무': [1, 2, 6, 9]}

In [17]:
dept_salary = emp_df.groupby('department')['salary']
print("부서별 평균 급여 : ")
print(dept_salary.mean())

print('부서별 최소 급여 : ')
print(dept_salary.min())

print('부서별 최고 급여 : ')
print(dept_salary.max())

부서별 평균 급여 :
department
IT    4566.666667
인사    4400.000000
재무    4975.000000
Name: salary, dtype: float64
부서별 최소 급여 :
department
IT    3800
인사    3500
재무    4200
Name: salary, dtype: int64
부서별 최고 급여 :
department
IT    6000
인사    5200
재무    6100
Name: salary, dtype: int64

In [28]:
# 직급별 인원수 조회
print(emp_df['job'].value_counts())
emp_df.groupby('job')['name'].count()

job
사원    3
대리    3
과장    2
팀장    2
Name: count, dtype: int64

job
과장    2
대리    3
사원    3
팀장    2
Name: name, dtype: int64

In [30]:
# 부서별 연봉그룹별 인원수 조회
# - 3000~4000, 4000~5000, 5000이상
# - 연봉그룹컬럼을 생성후 그룹핑
def set_salary_group(salary):
    if 3000 <= salary < 4000:
        return '3000대'
    elif 4000 <= salary < 5000:
        return '4000대'
    else:
        return '5000대이상'


# apply(함수): df, ser의 각 요소에 함수를 적용
emp_df['salary_group'] = emp_df['salary'].apply(set_salary_group)
# print(emp_df) #salary_group 컬럼 추가 확인

print(emp_df.groupby(['department', 'salary_group'])['name'].count())
print('-' * 30)
print(emp_df[['department', 'salary_group']].value_counts())

department  salary_group
IT          3000대           2
            5000대이상         1
인사          3000대           1
            4000대           1
            5000대이상         1
재무          4000대           2
            5000대이상         2
Name: name, dtype: int64
------------------------------
department  salary_group
재무          5000대이상         2
            4000대           2
IT          3000대           2
인사          3000대           1
IT          5000대이상         1
인사          4000대           1
            5000대이상         1
Name: count, dtype: int64

In [31]:
# agg() 집계 함수 모음
# - 그룹화된 데이터에서 원하는 집계 연산을 적용하여 요약 통계를 반환한다
emp_df.groupby('department')['salary'].agg(['mean', 'min', 'max', 'std', 'count'])

                   mean   min   max          std  count
department
IT          4566.666667  3800  6000  1242.309677      3
인사          4400.000000  3500  5200   854.400375      3
재무          4975.000000  4200  6100   818.026079      4

In [32]:
emp_df.groupby('department').agg({
    'salary': 'mean',
    'hire_date': 'min'
})

                 salary  hire_date
department
IT          4566.666667 2017-09-25
인사          4400.000000 2016-11-30
재무          4975.000000 2017-12-15

In [33]:
dept_salary_df = emp_df.groupby("department", as_index=False).agg(
    employee_count=("name", "count"),
    avg_salary=("salary", "mean"),
    min_salary=("salary", "min"),
    max_salary=("salary", "max")
)

dept_salary_df["avg_salary"] = dept_salary_df["avg_salary"].round(1)
display(dept_salary_df)

  department  employee_count  avg_salary  min_salary  max_salary
0         IT               3      4566.7        3800        6000
1         인사               3      4400.0        3500        5200
2         재무               4      4975.0        4200        6100

In [40]:
# fillter() : 그룹에 대한 조건을 기준으로 그룹 전체를 남긴다
# == 그룹 필터링

emp_df.groupby('department')['salary'].mean()


def func1():
    return emp_df['salary'].mean() > 4500


#부서 급여 평균이 4500 초과인 부서만 출력
# emp_df.groupby('department').filter(
#     lambda  group: group['salary'].mean() > 4500)
# emp_df.groupby('department').filter(func1)

emp_df.groupby('department').filter(
    lambda a: a['salary'].mean() > 4500
)

# display(emp)

  name department job branch  salary  hire_date salary_group
1  박보검         재무  과장     부산    5000 2018-07-10      5000대이상
2  송혜교         재무  대리     서울    4200 2019-05-20        4000대
3  아이유         IT  사원     부산    3800 2021-01-10        3000대
4   공유         IT  팀장     서울    6000 2017-09-25      5000대이상
6   수지         재무  대리     서울    4600 2020-06-12        4000대
8  강동원         IT  사원     서울    3900 2022-04-01        3000대
9   윤아         재무  팀장     부산    6100 2017-12-15      5000대이상

## pivot_table
- 기본 기능: 데이터를 행, 열, 값으로 재구성하여 테이블을 만든다.
- 사용 방식: 단순히 재구성하려는 index, columns, values를 지정한다.
- 중복 허용: 동일한 index와 columns 조합이 중복될 경우, aggfunc를 통해 해당 중복된 데이터를 집계할 수 있다.
- 집계 함수 지원: aggfunc 매개변수를 사용하여 sum, mean, count 등의 집계 함수를 적용할 수 있다. (기본값: mean)
- 결측치 채움: fill_value 매개변수를 사용하여 결측치를 채울 수 있다.

In [41]:
data = {
    '날짜': [
        '2024-01-01', '2024-01-01', '2024-01-01', '2024-01-01',
        '2024-01-02', '2024-01-02', '2024-01-02', '2024-01-02',
        '2024-01-03', '2024-01-03'
    ],
    '상품': [
        '아이폰 14', '갤럭시 S23', '아이패드 프로', '아이폰 14',
        '아이폰 14', '갤럭시 S23', '아이패드 프로', '갤럭시 S23',
        '맥북 프로', '아이폰 14'
    ],
    '판매량': [15, 30, 5, 10, 20, 25, 10, 5, 8, 12],
    '가격': [1000, 900, 800, 1000, 1000, 900, 800, 900, 2000, 1000]
}
sale_df = pd.DataFrame(data)
sale_df

           날짜       상품  판매량    가격
0  2024-01-01   아이폰 14   15  1000
1  2024-01-01  갤럭시 S23   30   900
2  2024-01-01  아이패드 프로    5   800
3  2024-01-01   아이폰 14   10  1000
4  2024-01-02   아이폰 14   20  1000
5  2024-01-02  갤럭시 S23   25   900
6  2024-01-02  아이패드 프로   10   800
7  2024-01-02  갤럭시 S23    5   900
8  2024-01-03    맥북 프로    8  2000
9  2024-01-03   아이폰 14   12  1000

In [42]:
# pivot_table
sale_pivot_df = pd.pivot_table(
    sale_df,
    index='날짜',  # 행 기준을 날짜로 설정
    columns='상품',  # 열 기준을 상품으로 설정
    values='판매량',  # 표 안에 채울 값
    fill_value=0,  # 값이 없는 조합은 0으로 채움
    aggfunc='sum',  # 같은 날짜/상품이 이려개면 판매량을 합산
    margins=True  # 행/열 합계 추가
)

sale_pivot_df

상품          갤럭시 S23  맥북 프로  아이패드 프로  아이폰 14  All
날짜
2024-01-01       30      0        5      25   60
2024-01-02       30      0       10      20   60
2024-01-03        0      8        0      12   20
All              60      8       15      57  140

## 타이타닉 데이터셋

In [54]:
titanic_df = pd.read_csv('./data/titanic.csv')

# 성별, 선실등급(pclass)별 생존률
pivot_td = pd.pivot_table(
    titanic_df,
    index='Pclass',
    columns='Sex',
    values='Survived',
    aggfunc='mean',
    margins=True

).round(2).reset_index(drop=True)

display(pivot_td)

pivot_td = pd.pivot_table(
    titanic_df,
    index='Pclass',
    columns='Sex',
    values='Survived',
    aggfunc='mean',
    margins=True
).round(2)

pivot_td = pivot_td.reset_index()
pivot_td.columns.name = None

display(pivot_td)

  Pclass  female  male   All
0      1    0.97  0.37  0.63
1      2    0.92  0.16  0.47
2      3    0.50  0.14  0.24
3    All    0.74  0.19  0.38